const SILVERA=7527,KLUTO=7317,PINTER=7298,RATMAN=389,BIG_RATMAN=390,VUKU=17;
const RING=1632,PASS1=1633,PASS2=1634,PASS_FINAL=1635,TOOTH=1636,BIG_TOOTH=1637,KLUTO_LETTER=1638,FOOTPRINT=1639,BOX1=1640,BOX2=1641;
const ACCEPT="ItemSound.quest_accept",ITEM="ItemSound.quest_itemget",MIDDLE="ItemSound.quest_middle",FINISH="ItemSound.quest_finish";
const service=()=>invoke("GameServer/Quest/QuestService"),page=(t,x,a="")=>`<html><body>${t}:<br>${x}<br><br>${a}</body></html>`,count=(s,i)=>s.session.actor.backpack.fetchItemFromSelfId(i)?.fetchAmount()||0;
// Every hand-out and its cond advance commit together.
const step=(s,{takes=[],gives=[],cond})=>require("../QuestStep").apply(s,{takes:takes.filter(([,n])=>n>0),gives,variables:cond===undefined?{...s.variables}:{...s.variables,cond:String(cond)}});
module.exports={id:418,name:"Path to Artisan",npcs:[SILVERA,KLUTO,PINTER],startNpcs:[SILVERA],killNpcs:[RATMAN,BIG_RATMAN,VUKU],eventNpc:e=>({start:SILVERA,letter:KLUTO,footprint:PINTER,box:PINTER})[e]??null,
async onEvent(s,e){const q=service(),a=s.session.actor;if(e==="start"&&!s.isStarted()&&!s.isCompleted()){if(Number(a.fetchClassId())!==53||Number(a.fetchLevel())<19||count(s,PASS_FINAL))return null;await s.setState("started");await s.set("cond",1);await q.giveItem(s.session,RING,1);s.playSound(ACCEPT);return page("Silvera","Bring ten Boogle Ratman Teeth and two Leader Teeth.");}if(e==="letter"&&s.getInt("cond")===3&&count(s,PASS1)){await step(s,{gives:[[KLUTO_LETTER,1]],cond:4});return page("Kluto","Take my letter to Pinter.");}if(e==="footprint"&&s.getInt("cond")===4&&count(s,KLUTO_LETTER)){await step(s,{takes:[[KLUTO_LETTER,count(s,KLUTO_LETTER)]],gives:[[FOOTPRINT,1]],cond:5});return page("Pinter","Recover the Stolen Secret Box from Vuku Orc Fighters.");}if(e==="box"&&s.getInt("cond")===6&&count(s,FOOTPRINT)&&count(s,BOX1)){await step(s,{takes:[[FOOTPRINT,count(s,FOOTPRINT)],[BOX1,count(s,BOX1)]],gives:[[BOX2,1],[PASS2,1]],cond:7});return page("Pinter","Return to Kluto.");}return null;},
async onTalk(s,n){const id=Number(n.fetchSelfId()),q=service();if(s.isCompleted())return page("Silvera","You have already completed the Path to Artisan.");if(!s.isStarted()){const a=s.session.actor;if(id!==SILVERA||Number(a.fetchClassId())!==53)return page("Quest","This path is not for your current class.");return Number(a.fetchLevel())<19?page("Silvera","Come back after reaching level 19."):page("Silvera","Do you seek the path of an Artisan?",'<a action="bypass -h quest 418 start">Accept the trial.</a>');}const c=s.getInt("cond");if(id===SILVERA){if(c<=2&&count(s,RING)&&count(s,TOOTH)>=10&&count(s,BIG_TOOTH)>=2){await step(s,{takes:[[RING,count(s,RING)],[TOOTH,count(s,TOOTH)],[BIG_TOOTH,count(s,BIG_TOOTH)]],gives:[[PASS1,1]],cond:3});return page("Silvera","Take the first pass to Kluto.");}return page("Silvera",`Boogle Ratman Teeth: ${count(s,TOOTH)}/10; Leader Teeth: ${count(s,BIG_TOOTH)}/2.`);}if(id===KLUTO){if(c===7&&count(s,PASS1)&&count(s,PASS2)&&count(s,BOX2)){const r=await q.awardFirstProfession(s, 56, [PASS1, PASS2, BOX2].map(id => [id, 1]));if(!r.ok)return page("Kluto","Your profession could not be granted. Keep the passes and try again."); s.playSound(FINISH); return page("Kluto","You have completed the Path to Artisan. Present your proof for class transfer at level 20.");}if(c===3&&count(s,PASS1))return page("Kluto","Accept my task.",'<a action="bypass -h quest 418 letter">Receive Kluto’s Letter.</a>');return page("Kluto","Complete Pinter's task.");}if(id===PINTER){if(c===4&&count(s,KLUTO_LETTER))return page("Pinter","Present Kluto's Letter.",'<a action="bypass -h quest 418 footprint">Receive the Footprint.</a>');if(c===6&&count(s,FOOTPRINT)&&count(s,BOX1))return page("Pinter","Present the Stolen Secret Box.",'<a action="bypass -h quest 418 box">Receive the second pass.</a>');return page("Pinter","Recover the Stolen Secret Box from Vuku Orc Fighters.");}return page("Quest","Continue your trial.");},
async onKill(s,n){if(!s.isStarted())return;const id=Number(n.fetchSelfId()),c=s.getInt("cond");if(id===RATMAN&&c<=2&&count(s,RING)&&count(s,TOOTH)<10&&Math.random()<.7){await step(s,{gives:[[TOOTH,1]]});s.playSound(count(s,TOOTH)===10&&count(s,BIG_TOOTH)>=2?MIDDLE:ITEM);}else if(id===BIG_RATMAN&&c<=2&&count(s,RING)&&count(s,BIG_TOOTH)<2&&Math.random()<.5){await step(s,{gives:[[BIG_TOOTH,1]]});s.playSound(count(s,BIG_TOOTH)===2&&count(s,TOOTH)>=10?MIDDLE:ITEM);}else if(id===VUKU&&c===5&&count(s,FOOTPRINT)&&!count(s,BOX1)&&Math.random()<.2){await step(s,{gives:[[BOX1,1]],cond:6});s.playSound(MIDDLE);}}
};
